// <auto-generated />
using System;
using MgeniTrack.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MgeniTrack.Migrations
{
    [DbContext(typeof(MgenitrackContext))]
    partial class MgenitrackContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_general_ci")
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MgeniTrack.Models.ActivityLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("log_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("ActionDetails")
                        .HasColumnType("text")
                        .HasColumnName("action_details");

                    b.Property<string>("ActionType")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("action_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ip_address");

                    b.Property<int?>("RelatedEntityId")
                        .HasColumnType("int(11)")
                        .HasColumnName("related_entity_id");

                    b.Property<string>("RelatedEntityType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("related_entity_type");

                    b.Property<DateTime?>("TimeStamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("time_stamp")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("user_agent");

                    b.Property<int?>("UserId")
                        .HasColumnType("int(11)")
                        .HasColumnName("user_id");

                    b.HasKey("LogId")
                        .HasName("PRIMARY");

                    b.HasIndex("UserId");

                    b.ToTable("activity_logs", (string)null);
                });

            modelBuilder.Entity("MgeniTrack.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("notification_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<bool>("IsEmailSent")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_email_sent");

                    b.Property<bool?>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_read")
                        .HasDefaultValueSql("'0'");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("NotificationType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("notification_type");

                    b.Property<int?>("ResidentId")
                        .HasColumnType("int(11)")
                        .HasColumnName("resident_id");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("title");

                    b.Property<int?>("VisitId")
                        .HasColumnType("int(11)")
                        .HasColumnName("visit_id");

                    b.HasKey("NotificationId")
                        .HasName("PRIMARY");

                    b.HasIndex("ResidentId");

                    b.HasIndex("VisitId");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("MgeniTrack.Models.Report", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("report_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<DateOnly?>("DateFrom")
                        .HasColumnType("date")
                        .HasColumnName("date_from");

                    b.Property<DateOnly?>("DateTo")
                        .HasColumnType("date")
                        .HasColumnName("date_to");

                    b.Property<string>("FileFormat")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("file_format");

                    b.Property<string>("FilePath")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("file_path");

                    b.Property<DateTime?>("GeneratedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("generated_at")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<int?>("GeneratedBy")
                        .HasColumnType("int(11)")
                        .HasColumnName("generated_by");

                    b.Property<string>("ReportType")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("report_type");

                    b.Property<int?>("TotalCheckIns")
                        .HasColumnType("int(11)")
                        .HasColumnName("total_check_ins");

                    b.Property<int?>("TotalCheckOuts")
                        .HasColumnType("int(11)")
                        .HasColumnName("total_check_outs");

                    b.Property<int?>("TotalVisitors")
                        .HasColumnType("int(11)")
                        .HasColumnName("total_visitors");

                    b.HasKey("ReportId")
                        .HasName("PRIMARY");

                    b.HasIndex("GeneratedBy");

                    b.ToTable("reports", (string)null);
                });

            modelBuilder.Entity("MgeniTrack.Models.Resident", b =>
                {
                    b.Property<int>("ResidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("resident_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ResidentId"));

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("house_number");

                    b.Property<int?>("UnitId")
                        .HasColumnType("int(11)")
                        .HasColumnName("unit_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int(11)")
                        .HasColumnName("user_id");

                    b.HasKey("ResidentId")
                        .HasName("PRIMARY");

                    b.HasIndex("UnitId");

                    b.HasIndex(new[] { "UserId" }, "user_id")
                        .IsUnique();

                    b.ToTable("residents", (string)null);
                });

            modelBuilder.Entity("MgeniTrack.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("role_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleDescription")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("role_description");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("role_name");

                    b.HasKey("RoleId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "RoleName" }, "role_name")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("MgeniTrack.Models.SystemSetting", b =>
                {
                    b.Property<int>("SettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("setting_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SettingId"));

                    b.Property<string>("SettingKey")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("setting_key");

                    b.Property<string>("SettingValue")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("setting_value");

                    b.Property<string>("SysDescription")
                        .HasColumnType("text")
                        .HasColumnName("sys_description");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int(11)")
                        .HasColumnName("updated_by");

                    b.HasKey("SettingId")
                        .HasName("PRIMARY");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("system_settings", (string)null);
                });

            modelBuilder.Entity("MgeniTrack.Models.Unit", b =>
                {
                    b.Property<int>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("unit_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UnitId"));

                    b.Property<string>("Block")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("block");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<int>("FloorNumber")
                        .HasColumnType("int(11)")
                        .HasColumnName("floor_number");

                    b.Property<bool>("IsOccupied")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_occupied");

                    b.Property<string>("UnitNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("unit_number");

                    b.Property<int>("UnitPosition")
                        .HasColumnType("int(11)")
                        .HasColumnName("unit_position");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasColumnType("enum('Residential','BnB')")
                        .HasColumnName("unit_type");

                    b.HasKey("UnitId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "UnitNumber" }, "unit_number")
                        .IsUnique();

                    b.ToTable("units", (string)null);
                });

            modelBuilder.Entity("MgeniTrack.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("user_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int(11)")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("firstname");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("enum('Male','Female','Other')")
                        .HasColumnName("gender");

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("id_number");

                    b.Property<DateTime?>("LastActivityAt")
                        .HasColumnType("datetime")
                        .HasColumnName("last_activity_at");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime")
                        .HasColumnName("last_login");

                    b.Property<string>("Passwordhash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("passwordhash");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Secondname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("secondname");

                    b.Property<DateTime?>("SessionExpiresAt")
                        .HasColumnType("datetime")
                        .HasColumnName("session_expires_at");

                    b.Property<string>("UserStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('Active','Inactive')")
                        .HasColumnName("user_status")
                        .HasDefaultValueSql("'Active'");

                    b.HasKey("UserId")
                        .HasName("PRIMARY");

                    b.HasIndex("CreatedBy");

                    b.HasIndex(new[] { "Email" }, "email")
                        .IsUnique();

                    b.HasIndex(new[] { "IdNumber" }, "id_number")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("MgeniTrack.Models.UserRole", b =>
                {
                    b.Property<int>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("user_role_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserRoleId"));

                    b.Property<DateTime?>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("assigned_at")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<int>("RoleId")
                        .HasColumnType("int(11)")
                        .HasColumnName("role_id");

                    b.Property<string>("Shift")
                        .HasColumnType("enum('Day','Night')")
                        .HasColumnName("shift");

                    b.Property<int>("UserId")
                        .HasColumnType("int(11)")
                        .HasColumnName("user_id");

                    b.Property<string>("UserStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('Active','Inactive')")
                        .HasColumnName("user_status")
                        .HasDefaultValueSql("'Active'");

                    b.HasKey("UserRoleId")
                        .HasName("PRIMARY");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "UserId", "RoleId" }, "user_id")
                        .IsUnique()
                        .HasDatabaseName("user_id1");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("MgeniTrack.Models.Visit", b =>
                {
                    b.Property<int>("VisitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("visit_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("VisitId"));

                    b.Property<string>("CarRegistration")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("car_registration");

                    b.Property<string>("CheckInMethod")
                        .HasColumnType("enum('QR','Manual')")
                        .HasColumnName("check_in_method");

                    b.Property<int?>("CheckedInBy")
                        .HasColumnType("int(11)")
                        .HasColumnName("checked_in_by");

                    b.Property<int?>("CheckedOutBy")
                        .HasColumnType("int(11)")
                        .HasColumnName("checked_out_by");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("HouseNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("house_number");

                    b.Property<int?>("InvitationId")
                        .HasColumnType("int(11)")
                        .HasColumnName("invitation_id");

                    b.Property<int?>("NumberOfOccupants")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("number_of_occupants")
                        .HasDefaultValueSql("'1'");

                    b.Property<string>("PurposeOfVisit")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("purpose_of_visit");

                    b.Property<string>("QrCode")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("qr_code");

                    b.Property<DateTime?>("TimeIn")
                        .HasColumnType("datetime")
                        .HasColumnName("time_in");

                    b.Property<DateTime?>("TimeOut")
                        .HasColumnType("datetime")
                        .HasColumnName("time_out");

                    b.Property<int?>("VisitDuration")
                        .HasColumnType("int(11)")
                        .HasColumnName("visit_duration");

                    b.Property<string>("VisitStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('CheckedIn','CheckedOut')")
                        .HasColumnName("visit_status")
                        .HasDefaultValueSql("'CheckedIn'");

                    b.Property<int>("VisitorId")
                        .HasColumnType("int(11)")
                        .HasColumnName("visitor_id");

                    b.HasKey("VisitId")
                        .HasName("PRIMARY");

                    b.HasIndex("CheckedInBy");

                    b.HasIndex("CheckedOutBy");

                    b.HasIndex("InvitationId");

                    b.HasIndex("VisitorId");

                    b.ToTable("visits", (string)null);
                });

            modelBuilder.Entity("MgeniTrack.Models.Visitor", b =>
                {
                    b.Property<int>("VisitorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("visitor_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("VisitorId"));

                    b.Property<string>("ContactNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("contact_number");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<DateTime?>("FirstVisitDate")
                        .HasColumnType("datetime")
                        .HasColumnName("first_visit_date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("full_name");

                    b.Property<string>("IdNumber")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("id_number");

                    b.Property<int?>("InvitedViaInvitationId")
                        .HasColumnType("int(11)")
                        .HasColumnName("invited_via_invitation_id");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("photo_url");

                    b.Property<int?>("TotalVisits")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("total_visits")
                        .HasDefaultValueSql("'0'");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("VisitorId")
                        .HasName("PRIMARY");

                    b.HasIndex("InvitedViaInvitationId");

                    b.ToTable("visitors", (string)null);
                });

            modelBuilder.Entity("MgeniTrack.Models.VisitorInvitation", b =>
                {
                    b.Property<int>("InvitationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("invitation_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("InvitationId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<DateOnly?>("ExpectedDate")
                        .HasColumnType("date")
                        .HasColumnName("expected_date");

                    b.Property<string>("InvitationToken")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("invitation_token");

                    b.Property<string>("PurposeOfVisit")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("purpose_of_visit");

                    b.Property<string>("QrCodePath")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("qr_code_path");

                    b.Property<int>("ResidentId")
                        .HasColumnType("int(11)")
                        .HasColumnName("resident_id");

                    b.Property<string>("VisitStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('Pending','Arrived','Expired','Cancelled')")
                        .HasColumnName("visit_status")
                        .HasDefaultValueSql("'Pending'");

                    b.Property<string>("VisitorEmail")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("visitor_email");

                    b.Property<string>("VisitorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("visitor_name");

                    b.Property<string>("VisitorPhone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("visitor_phone");

                    b.HasKey("InvitationId")
                        .HasName("PRIMARY");

                    b.HasIndex("ResidentId");

                    b.HasIndex(new[] { "InvitationToken" }, "invitation_token")
                        .IsUnique();

                    b.ToTable("visitor_invitations", (string)null);
                });

            modelBuilder.Entity("MgeniTrack.Models.ActivityLog", b =>
                {
                    b.HasOne("MgeniTrack.Models.User", "User")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("UserId")
                        .HasConstraintName("activity_logs_ibfk_1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MgeniTrack.Models.Notification", b =>
                {
                    b.HasOne("MgeniTrack.Models.Resident", "Resident")
                        .WithMany("Notifications")
                        .HasForeignKey("ResidentId")
                        .HasConstraintName("notifications_ibfk_1");

                    b.HasOne("MgeniTrack.Models.Visit", "Visit")
                        .WithMany("Notifications")
                        .HasForeignKey("VisitId")
                        .HasConstraintName("notifications_ibfk_2");

                    b.Navigation("Resident");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("MgeniTrack.Models.Report", b =>
                {
                    b.HasOne("MgeniTrack.Models.User", "GeneratedByNavigation")
                        .WithMany("Reports")
                        .HasForeignKey("GeneratedBy")
                        .HasConstraintName("reports_ibfk_1");

                    b.Navigation("GeneratedByNavigation");
                });

            modelBuilder.Entity("MgeniTrack.Models.Resident", b =>
                {
                    b.HasOne("MgeniTrack.Models.Unit", "Unit")
                        .WithMany("Residents")
                        .HasForeignKey("UnitId")
                        .HasConstraintName("fk_residents_unit");

                    b.HasOne("MgeniTrack.Models.User", "User")
                        .WithOne("Resident")
                        .HasForeignKey("MgeniTrack.Models.Resident", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("residents_ibfk_1");

                    b.Navigation("Unit");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MgeniTrack.Models.SystemSetting", b =>
                {
                    b.HasOne("MgeniTrack.Models.User", "UpdatedByNavigation")
                        .WithMany("SystemSettings")
                        .HasForeignKey("UpdatedBy")
                        .HasConstraintName("system_settings_ibfk_1");

                    b.Navigation("UpdatedByNavigation");
                });

            modelBuilder.Entity("MgeniTrack.Models.User", b =>
                {
                    b.HasOne("MgeniTrack.Models.User", "CreatedByNavigation")
                        .WithMany("InverseCreatedByNavigation")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("users_ibfk_1");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("MgeniTrack.Models.UserRole", b =>
                {
                    b.HasOne("MgeniTrack.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_roles_ibfk_2");

                    b.HasOne("MgeniTrack.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_roles_ibfk_1");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MgeniTrack.Models.Visit", b =>
                {
                    b.HasOne("MgeniTrack.Models.User", "CheckedInByNavigation")
                        .WithMany("VisitCheckedInByNavigations")
                        .HasForeignKey("CheckedInBy")
                        .HasConstraintName("visits_ibfk_2");

                    b.HasOne("MgeniTrack.Models.User", "CheckedOutByNavigation")
                        .WithMany("VisitCheckedOutByNavigations")
                        .HasForeignKey("CheckedOutBy")
                        .HasConstraintName("visits_ibfk_3");

                    b.HasOne("MgeniTrack.Models.VisitorInvitation", "Invitation")
                        .WithMany("Visits")
                        .HasForeignKey("InvitationId")
                        .HasConstraintName("visits_ibfk_4");

                    b.HasOne("MgeniTrack.Models.Visitor", "Visitor")
                        .WithMany("Visits")
                        .HasForeignKey("VisitorId")
                        .IsRequired()
                        .HasConstraintName("visits_ibfk_1");

                    b.Navigation("CheckedInByNavigation");

                    b.Navigation("CheckedOutByNavigation");

                    b.Navigation("Invitation");

                    b.Navigation("Visitor");
                });

            modelBuilder.Entity("MgeniTrack.Models.Visitor", b =>
                {
                    b.HasOne("MgeniTrack.Models.VisitorInvitation", "InvitedViaInvitation")
                        .WithMany("Visitors")
                        .HasForeignKey("InvitedViaInvitationId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("visitors_ibfk_1");

                    b.Navigation("InvitedViaInvitation");
                });

            modelBuilder.Entity("MgeniTrack.Models.VisitorInvitation", b =>
                {
                    b.HasOne("MgeniTrack.Models.Resident", "Resident")
                        .WithMany("VisitorInvitations")
                        .HasForeignKey("ResidentId")
                        .IsRequired()
                        .HasConstraintName("visitor_invitations_ibfk_1");

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("MgeniTrack.Models.Resident", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("VisitorInvitations");
                });

            modelBuilder.Entity("MgeniTrack.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("MgeniTrack.Models.Unit", b =>
                {
                    b.Navigation("Residents");
                });

            modelBuilder.Entity("MgeniTrack.Models.User", b =>
                {
                    b.Navigation("ActivityLogs");

                    b.Navigation("InverseCreatedByNavigation");

                    b.Navigation("Reports");

                    b.Navigation("Resident");

                    b.Navigation("SystemSettings");

                    b.Navigation("UserRoles");

                    b.Navigation("VisitCheckedInByNavigations");

                    b.Navigation("VisitCheckedOutByNavigations");
                });

            modelBuilder.Entity("MgeniTrack.Models.Visit", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("MgeniTrack.Models.Visitor", b =>
                {
                    b.Navigation("Visits");
                });

            modelBuilder.Entity("MgeniTrack.Models.VisitorInvitation", b =>
                {
                    b.Navigation("Visitors");

                    b.Navigation("Visits");
                });
#pragma warning restore 612, 618
        }
    }
}
